# Étape 1 : Construction du Frontend (Vite)
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2 : Configuration du serveur PHP / Apache
FROM php:8.2-apache
RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN a2enmod rewrite

# Copier le Frontend compilé vers le serveur web
COPY --from=build /app/dist /var/www/html

# Copier le dossier Backend (PHP)
COPY backend /var/www/html/backend

# Permissions
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80